"""baseline schema

Revision ID: cc0c0227a415
Revises: 
Create Date: 2026-05-30 23:37:08.482992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0c0227a415'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('scheduling_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('days_json', sa.Text(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('action_params_json', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_username', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('target_label', sa.String(length=255), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('group_lexicons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_lexicons_created_by'), 'group_lexicons', ['created_by'], unique=False)
    op.create_index(op.f('ix_group_lexicons_group_id'), 'group_lexicons', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_lexicons_name'), 'group_lexicons', ['name'], unique=False)
    op.create_table('group_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_membership')
    )
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_user_id'), 'group_memberships', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('processing_mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_owner_id'), 'jobs', ['owner_id'], unique=False)
    op.create_table('voice_subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_subjects_created_by'), 'voice_subjects', ['created_by'], unique=False)
    op.create_index(op.f('ix_voice_subjects_display_name'), 'voice_subjects', ['display_name'], unique=False)
    op.create_index(op.f('ix_voice_subjects_group_id'), 'voice_subjects', ['group_id'], unique=False)
    op.create_table('group_lexicon_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lexicon_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('variants_json', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('replace_by', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lexicon_id'], ['group_lexicons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_lexicon_entries_lexicon_id'), 'group_lexicon_entries', ['lexicon_id'], unique=False)
    op.create_index(op.f('ix_group_lexicon_entries_term'), 'group_lexicon_entries', ['term'], unique=False)
    op.create_table('job_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('base_priority', sa.Integer(), nullable=False),
    sa.Column('aging_bonus', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_phase', sa.String(length=30), nullable=True),
    sa.Column('vram_profile_json', sa.Text(), nullable=True),
    sa.Column('gpu_index', sa.Integer(), nullable=True),
    sa.Column('last_aging_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_by', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['paused_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_queue_job_id'), 'job_queue', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_queue_scheduled_at'), 'job_queue', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_job_queue_status'), 'job_queue', ['status'], unique=False)
    op.create_index(op.f('ix_job_queue_submitted_at'), 'job_queue', ['submitted_at'], unique=False)
    op.create_table('voice_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('form_version', sa.String(length=80), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('proof_path', sa.String(length=500), nullable=False),
    sa.Column('proof_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('revocation_reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['voice_subjects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_consents_status'), 'voice_consents', ['status'], unique=False)
    op.create_index(op.f('ix_voice_consents_subject_id'), 'voice_consents', ['subject_id'], unique=False)
    op.create_index(op.f('ix_voice_consents_uploaded_by'), 'voice_consents', ['uploaded_by'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('consent_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('embedding_backend', sa.String(length=80), nullable=False),
    sa.Column('embedding_model_id', sa.String(length=255), nullable=False),
    sa.Column('embedding_model_revision', sa.String(length=255), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('embedding_version', sa.String(length=40), nullable=False),
    sa.Column('normalization', sa.String(length=40), nullable=False),
    sa.Column('embedding_stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=80), nullable=False),
    sa.Column('embedding_blob', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_sha256', sa.String(length=64), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('speech_duration_s', sa.Float(), nullable=False),
    sa.Column('quality_status', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consent_id'], ['voice_consents.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['voice_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_consent_id'), 'voice_profiles', ['consent_id'], unique=False)
    op.create_index(op.f('ix_voice_profiles_created_by'), 'voice_profiles', ['created_by'], unique=False)
    op.create_index(op.f('ix_voice_profiles_group_id'), 'voice_profiles', ['group_id'], unique=False)
    op.create_index(op.f('ix_voice_profiles_status'), 'voice_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_voice_profiles_subject_id'), 'voice_profiles', ['subject_id'], unique=False)
    op.create_table('voice_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['voice_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_audit_events_actor_id'), 'voice_audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_voice_audit_events_event_type'), 'voice_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_voice_audit_events_profile_id'), 'voice_audit_events', ['profile_id'], unique=False)
    op.create_index(op.f('ix_voice_audit_events_subject_id'), 'voice_audit_events', ['subject_id'], unique=False)
    op.create_table('voice_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_id', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_kind', sa.String(length=40), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['voice_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_matches_created_by'), 'voice_matches', ['created_by'], unique=False)
    op.create_index(op.f('ix_voice_matches_decision'), 'voice_matches', ['decision'], unique=False)
    op.create_index(op.f('ix_voice_matches_job_id'), 'voice_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_voice_matches_profile_id'), 'voice_matches', ['profile_id'], unique=False)
    op.create_index(op.f('ix_voice_matches_speaker_id'), 'voice_matches', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_voice_matches_subject_id'), 'voice_matches', ['subject_id'], unique=False)
    op.create_table('voice_reference_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_reference_files_profile_id'), 'voice_reference_files', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_reference_files_profile_id'), table_name='voice_reference_files')
    op.drop_table('voice_reference_files')
    op.drop_index(op.f('ix_voice_matches_subject_id'), table_name='voice_matches')
    op.drop_index(op.f('ix_voice_matches_speaker_id'), table_name='voice_matches')
    op.drop_index(op.f('ix_voice_matches_profile_id'), table_name='voice_matches')
    op.drop_index(op.f('ix_voice_matches_job_id'), table_name='voice_matches')
    op.drop_index(op.f('ix_voice_matches_decision'), table_name='voice_matches')
    op.drop_index(op.f('ix_voice_matches_created_by'), table_name='voice_matches')
    op.drop_table('voice_matches')
    op.drop_index(op.f('ix_voice_audit_events_subject_id'), table_name='voice_audit_events')
    op.drop_index(op.f('ix_voice_audit_events_profile_id'), table_name='voice_audit_events')
    op.drop_index(op.f('ix_voice_audit_events_event_type'), table_name='voice_audit_events')
    op.drop_index(op.f('ix_voice_audit_events_actor_id'), table_name='voice_audit_events')
    op.drop_table('voice_audit_events')
    op.drop_index(op.f('ix_voice_profiles_subject_id'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_status'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_group_id'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_created_by'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_consent_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_voice_consents_uploaded_by'), table_name='voice_consents')
    op.drop_index(op.f('ix_voice_consents_subject_id'), table_name='voice_consents')
    op.drop_index(op.f('ix_voice_consents_status'), table_name='voice_consents')
    op.drop_table('voice_consents')
    op.drop_index(op.f('ix_job_queue_submitted_at'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_status'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_scheduled_at'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_job_id'), table_name='job_queue')
    op.drop_table('job_queue')
    op.drop_index(op.f('ix_group_lexicon_entries_term'), table_name='group_lexicon_entries')
    op.drop_index(op.f('ix_group_lexicon_entries_lexicon_id'), table_name='group_lexicon_entries')
    op.drop_table('group_lexicon_entries')
    op.drop_index(op.f('ix_voice_subjects_group_id'), table_name='voice_subjects')
    op.drop_index(op.f('ix_voice_subjects_display_name'), table_name='voice_subjects')
    op.drop_index(op.f('ix_voice_subjects_created_by'), table_name='voice_subjects')
    op.drop_table('voice_subjects')
    op.drop_index(op.f('ix_jobs_owner_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_group_memberships_user_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_group_lexicons_name'), table_name='group_lexicons')
    op.drop_index(op.f('ix_group_lexicons_group_id'), table_name='group_lexicons')
    op.drop_index(op.f('ix_group_lexicons_created_by'), table_name='group_lexicons')
    op.drop_table('group_lexicons')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('scheduling_windows')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
